// --~--~--~--~----~--~--~--~----~--~--~--~----~--~--~--~----~--~--~--~--
// Copyright (c) [2010-2014] The Regents of the University of California
// All rights reserved.
// Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:
// * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
// * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
// * Neither the name of The Regents of the University of California nor the project name nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
// NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
// --~--~--~--~----~--~--~--~----~--~--~--~----~--~--~--~----~--~--~--~--
﻿
namespace mjr.CodeGen
{
    //$vals="Undefined","String","Double","Int","Boolean","Null","Object","Function","Array","Property","DValue","Unknown"; 
    //foreach( $i in $vals) {foreach($j in $vals) {"{0}_{1} = mdr.ValueTypes.{0} << 4 | mdr.ValueTypes.{1}," -f $i, $j}}

#if NONE
    enum ValueTypePairs : byte
    {
        Undefined_Undefined = mdr.ValueTypes.Undefined << 4 | mdr.ValueTypes.Undefined,
        Undefined_String = mdr.ValueTypes.Undefined << 4 | mdr.ValueTypes.String,
        Undefined_Double = mdr.ValueTypes.Undefined << 4 | mdr.ValueTypes.Double,
        Undefined_Int = mdr.ValueTypes.Undefined << 4 | mdr.ValueTypes.Int32,
        Undefined_Boolean = mdr.ValueTypes.Undefined << 4 | mdr.ValueTypes.Boolean,
        Undefined_Null = mdr.ValueTypes.Undefined << 4 | mdr.ValueTypes.Null,
        Undefined_Object = mdr.ValueTypes.Undefined << 4 | mdr.ValueTypes.Object,
        Undefined_Function = mdr.ValueTypes.Undefined << 4 | mdr.ValueTypes.Function,
        Undefined_Array = mdr.ValueTypes.Undefined << 4 | mdr.ValueTypes.Array,
        Undefined_Property = mdr.ValueTypes.Undefined << 4 | mdr.ValueTypes.Property,
        Undefined_DValue = mdr.ValueTypes.Undefined << 4 | mdr.ValueTypes.DValue,
        Undefined_Unknown = mdr.ValueTypes.Undefined << 4 | mdr.ValueTypes.Unknown,
        String_Undefined = mdr.ValueTypes.String << 4 | mdr.ValueTypes.Undefined,
        String_String = mdr.ValueTypes.String << 4 | mdr.ValueTypes.String,
        String_Double = mdr.ValueTypes.String << 4 | mdr.ValueTypes.Double,
        String_Int = mdr.ValueTypes.String << 4 | mdr.ValueTypes.Int32,
        String_Boolean = mdr.ValueTypes.String << 4 | mdr.ValueTypes.Boolean,
        String_Null = mdr.ValueTypes.String << 4 | mdr.ValueTypes.Null,
        String_Object = mdr.ValueTypes.String << 4 | mdr.ValueTypes.Object,
        String_Function = mdr.ValueTypes.String << 4 | mdr.ValueTypes.Function,
        String_Array = mdr.ValueTypes.String << 4 | mdr.ValueTypes.Array,
        String_Property = mdr.ValueTypes.String << 4 | mdr.ValueTypes.Property,
        String_DValue = mdr.ValueTypes.String << 4 | mdr.ValueTypes.DValue,
        String_Unknown = mdr.ValueTypes.String << 4 | mdr.ValueTypes.Unknown,
        Double_Undefined = mdr.ValueTypes.Double << 4 | mdr.ValueTypes.Undefined,
        Double_String = mdr.ValueTypes.Double << 4 | mdr.ValueTypes.String,
        Double_Double = mdr.ValueTypes.Double << 4 | mdr.ValueTypes.Double,
        Double_Int = mdr.ValueTypes.Double << 4 | mdr.ValueTypes.Int32,
        Double_Boolean = mdr.ValueTypes.Double << 4 | mdr.ValueTypes.Boolean,
        Double_Null = mdr.ValueTypes.Double << 4 | mdr.ValueTypes.Null,
        Double_Object = mdr.ValueTypes.Double << 4 | mdr.ValueTypes.Object,
        Double_Function = mdr.ValueTypes.Double << 4 | mdr.ValueTypes.Function,
        Double_Array = mdr.ValueTypes.Double << 4 | mdr.ValueTypes.Array,
        Double_Property = mdr.ValueTypes.Double << 4 | mdr.ValueTypes.Property,
        Double_DValue = mdr.ValueTypes.Double << 4 | mdr.ValueTypes.DValue,
        Double_Unknown = mdr.ValueTypes.Double << 4 | mdr.ValueTypes.Unknown,
        Int_Undefined = mdr.ValueTypes.Int32 << 4 | mdr.ValueTypes.Undefined,
        Int_String = mdr.ValueTypes.Int32 << 4 | mdr.ValueTypes.String,
        Int_Double = mdr.ValueTypes.Int32 << 4 | mdr.ValueTypes.Double,
        Int_Int = mdr.ValueTypes.Int32 << 4 | mdr.ValueTypes.Int32,
        Int_Boolean = mdr.ValueTypes.Int32 << 4 | mdr.ValueTypes.Boolean,
        Int_Null = mdr.ValueTypes.Int32 << 4 | mdr.ValueTypes.Null,
        Int_Object = mdr.ValueTypes.Int32 << 4 | mdr.ValueTypes.Object,
        Int_Function = mdr.ValueTypes.Int32 << 4 | mdr.ValueTypes.Function,
        Int_Array = mdr.ValueTypes.Int32 << 4 | mdr.ValueTypes.Array,
        Int_Property = mdr.ValueTypes.Int32 << 4 | mdr.ValueTypes.Property,
        Int_DValue = mdr.ValueTypes.Int32 << 4 | mdr.ValueTypes.DValue,
        Int_Unknown = mdr.ValueTypes.Int32 << 4 | mdr.ValueTypes.Unknown,
        Boolean_Undefined = mdr.ValueTypes.Boolean << 4 | mdr.ValueTypes.Undefined,
        Boolean_String = mdr.ValueTypes.Boolean << 4 | mdr.ValueTypes.String,
        Boolean_Double = mdr.ValueTypes.Boolean << 4 | mdr.ValueTypes.Double,
        Boolean_Int = mdr.ValueTypes.Boolean << 4 | mdr.ValueTypes.Int32,
        Boolean_Boolean = mdr.ValueTypes.Boolean << 4 | mdr.ValueTypes.Boolean,
        Boolean_Null = mdr.ValueTypes.Boolean << 4 | mdr.ValueTypes.Null,
        Boolean_Object = mdr.ValueTypes.Boolean << 4 | mdr.ValueTypes.Object,
        Boolean_Function = mdr.ValueTypes.Boolean << 4 | mdr.ValueTypes.Function,
        Boolean_Array = mdr.ValueTypes.Boolean << 4 | mdr.ValueTypes.Array,
        Boolean_Property = mdr.ValueTypes.Boolean << 4 | mdr.ValueTypes.Property,
        Boolean_DValue = mdr.ValueTypes.Boolean << 4 | mdr.ValueTypes.DValue,
        Boolean_Unknown = mdr.ValueTypes.Boolean << 4 | mdr.ValueTypes.Unknown,
        Null_Undefined = mdr.ValueTypes.Null << 4 | mdr.ValueTypes.Undefined,
        Null_String = mdr.ValueTypes.Null << 4 | mdr.ValueTypes.String,
        Null_Double = mdr.ValueTypes.Null << 4 | mdr.ValueTypes.Double,
        Null_Int = mdr.ValueTypes.Null << 4 | mdr.ValueTypes.Int32,
        Null_Boolean = mdr.ValueTypes.Null << 4 | mdr.ValueTypes.Boolean,
        Null_Null = mdr.ValueTypes.Null << 4 | mdr.ValueTypes.Null,
        Null_Object = mdr.ValueTypes.Null << 4 | mdr.ValueTypes.Object,
        Null_Function = mdr.ValueTypes.Null << 4 | mdr.ValueTypes.Function,
        Null_Array = mdr.ValueTypes.Null << 4 | mdr.ValueTypes.Array,
        Null_Property = mdr.ValueTypes.Null << 4 | mdr.ValueTypes.Property,
        Null_DValue = mdr.ValueTypes.Null << 4 | mdr.ValueTypes.DValue,
        Null_Unknown = mdr.ValueTypes.Null << 4 | mdr.ValueTypes.Unknown,
        Object_Undefined = mdr.ValueTypes.Object << 4 | mdr.ValueTypes.Undefined,
        Object_String = mdr.ValueTypes.Object << 4 | mdr.ValueTypes.String,
        Object_Double = mdr.ValueTypes.Object << 4 | mdr.ValueTypes.Double,
        Object_Int = mdr.ValueTypes.Object << 4 | mdr.ValueTypes.Int32,
        Object_Boolean = mdr.ValueTypes.Object << 4 | mdr.ValueTypes.Boolean,
        Object_Null = mdr.ValueTypes.Object << 4 | mdr.ValueTypes.Null,
        Object_Object = mdr.ValueTypes.Object << 4 | mdr.ValueTypes.Object,
        Object_Function = mdr.ValueTypes.Object << 4 | mdr.ValueTypes.Function,
        Object_Array = mdr.ValueTypes.Object << 4 | mdr.ValueTypes.Array,
        Object_Property = mdr.ValueTypes.Object << 4 | mdr.ValueTypes.Property,
        Object_DValue = mdr.ValueTypes.Object << 4 | mdr.ValueTypes.DValue,
        Object_Unknown = mdr.ValueTypes.Object << 4 | mdr.ValueTypes.Unknown,
        Function_Undefined = mdr.ValueTypes.Function << 4 | mdr.ValueTypes.Undefined,
        Function_String = mdr.ValueTypes.Function << 4 | mdr.ValueTypes.String,
        Function_Double = mdr.ValueTypes.Function << 4 | mdr.ValueTypes.Double,
        Function_Int = mdr.ValueTypes.Function << 4 | mdr.ValueTypes.Int32,
        Function_Boolean = mdr.ValueTypes.Function << 4 | mdr.ValueTypes.Boolean,
        Function_Null = mdr.ValueTypes.Function << 4 | mdr.ValueTypes.Null,
        Function_Object = mdr.ValueTypes.Function << 4 | mdr.ValueTypes.Object,
        Function_Function = mdr.ValueTypes.Function << 4 | mdr.ValueTypes.Function,
        Function_Array = mdr.ValueTypes.Function << 4 | mdr.ValueTypes.Array,
        Function_Property = mdr.ValueTypes.Function << 4 | mdr.ValueTypes.Property,
        Function_DValue = mdr.ValueTypes.Function << 4 | mdr.ValueTypes.DValue,
        Function_Unknown = mdr.ValueTypes.Function << 4 | mdr.ValueTypes.Unknown,
        Array_Undefined = mdr.ValueTypes.Array << 4 | mdr.ValueTypes.Undefined,
        Array_String = mdr.ValueTypes.Array << 4 | mdr.ValueTypes.String,
        Array_Double = mdr.ValueTypes.Array << 4 | mdr.ValueTypes.Double,
        Array_Int = mdr.ValueTypes.Array << 4 | mdr.ValueTypes.Int32,
        Array_Boolean = mdr.ValueTypes.Array << 4 | mdr.ValueTypes.Boolean,
        Array_Null = mdr.ValueTypes.Array << 4 | mdr.ValueTypes.Null,
        Array_Object = mdr.ValueTypes.Array << 4 | mdr.ValueTypes.Object,
        Array_Function = mdr.ValueTypes.Array << 4 | mdr.ValueTypes.Function,
        Array_Array = mdr.ValueTypes.Array << 4 | mdr.ValueTypes.Array,
        Array_Property = mdr.ValueTypes.Array << 4 | mdr.ValueTypes.Property,
        Array_DValue = mdr.ValueTypes.Array << 4 | mdr.ValueTypes.DValue,
        Array_Unknown = mdr.ValueTypes.Array << 4 | mdr.ValueTypes.Unknown,
        Property_Undefined = mdr.ValueTypes.Property << 4 | mdr.ValueTypes.Undefined,
        Property_String = mdr.ValueTypes.Property << 4 | mdr.ValueTypes.String,
        Property_Double = mdr.ValueTypes.Property << 4 | mdr.ValueTypes.Double,
        Property_Int = mdr.ValueTypes.Property << 4 | mdr.ValueTypes.Int32,
        Property_Boolean = mdr.ValueTypes.Property << 4 | mdr.ValueTypes.Boolean,
        Property_Null = mdr.ValueTypes.Property << 4 | mdr.ValueTypes.Null,
        Property_Object = mdr.ValueTypes.Property << 4 | mdr.ValueTypes.Object,
        Property_Function = mdr.ValueTypes.Property << 4 | mdr.ValueTypes.Function,
        Property_Array = mdr.ValueTypes.Property << 4 | mdr.ValueTypes.Array,
        Property_Property = mdr.ValueTypes.Property << 4 | mdr.ValueTypes.Property,
        Property_DValue = mdr.ValueTypes.Property << 4 | mdr.ValueTypes.DValue,
        Property_Unknown = mdr.ValueTypes.Property << 4 | mdr.ValueTypes.Unknown,
        DValue_Undefined = mdr.ValueTypes.DValue << 4 | mdr.ValueTypes.Undefined,
        DValue_String = mdr.ValueTypes.DValue << 4 | mdr.ValueTypes.String,
        DValue_Double = mdr.ValueTypes.DValue << 4 | mdr.ValueTypes.Double,
        DValue_Int = mdr.ValueTypes.DValue << 4 | mdr.ValueTypes.Int32,
        DValue_Boolean = mdr.ValueTypes.DValue << 4 | mdr.ValueTypes.Boolean,
        DValue_Null = mdr.ValueTypes.DValue << 4 | mdr.ValueTypes.Null,
        DValue_Object = mdr.ValueTypes.DValue << 4 | mdr.ValueTypes.Object,
        DValue_Function = mdr.ValueTypes.DValue << 4 | mdr.ValueTypes.Function,
        DValue_Array = mdr.ValueTypes.DValue << 4 | mdr.ValueTypes.Array,
        DValue_Property = mdr.ValueTypes.DValue << 4 | mdr.ValueTypes.Property,
        DValue_DValue = mdr.ValueTypes.DValue << 4 | mdr.ValueTypes.DValue,
        DValue_Unknown = mdr.ValueTypes.DValue << 4 | mdr.ValueTypes.Unknown,
        Unknown_Undefined = mdr.ValueTypes.Unknown << 4 | mdr.ValueTypes.Undefined,
        Unknown_String = mdr.ValueTypes.Unknown << 4 | mdr.ValueTypes.String,
        Unknown_Double = mdr.ValueTypes.Unknown << 4 | mdr.ValueTypes.Double,
        Unknown_Int = mdr.ValueTypes.Unknown << 4 | mdr.ValueTypes.Int32,
        Unknown_Boolean = mdr.ValueTypes.Unknown << 4 | mdr.ValueTypes.Boolean,
        Unknown_Null = mdr.ValueTypes.Unknown << 4 | mdr.ValueTypes.Null,
        Unknown_Object = mdr.ValueTypes.Unknown << 4 | mdr.ValueTypes.Object,
        Unknown_Function = mdr.ValueTypes.Unknown << 4 | mdr.ValueTypes.Function,
        Unknown_Array = mdr.ValueTypes.Unknown << 4 | mdr.ValueTypes.Array,
        Unknown_Property = mdr.ValueTypes.Unknown << 4 | mdr.ValueTypes.Property,
        Unknown_DValue = mdr.ValueTypes.Unknown << 4 | mdr.ValueTypes.DValue,
        Unknown_Unknown = mdr.ValueTypes.Unknown << 4 | mdr.ValueTypes.Unknown,
    }
#endif
}
